version: '3'
services: 
    nginx:
        image: nginx:latest
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports: 
            - 50051:50051
        depends_on: 
            - server1
            - server2
            - server3

    server1:
        image: grpc_example:latest
        command: go run ./main.go :50051 "server1"

    server2:
        image: grpc_example:latest
        command: go run ./main.go :50051 "server2"

    server3:
        image: grpc_example:latest
        command: go run ./main.go :50051 "server3"
